name: 京东家庭号

on:
    workflow_dispatch:
    schedule:
        - cron: "1 0,1,5,8,16,17 * * *"
    watch:
        types: [jd_family]
        
jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 10.x
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x
            - name: npm install
              run: |
                  npm install
            - name: "运行 【京东家庭号】"
              run: |
                  node jd_family.js
              env:
                  JD_COOKIE: ${{ secrets.JD_COOKIE || github.event.client_payload.JD_COOKIE }}
                  PUSH_KEY: ${{ secrets.PUSH_KEY }} || github.event.client_payload.PUSH_KEY }}
